### ISSUE TITLE
Error with Extensions?

### ISSUE THREAD

**Issue by Killerman234** [nosoop/SMExt-TF2Items#3]
![image](https://github.com/nosoop/SMExt-TF2Items/assets/167474029/67a7725c-03f3-4040-9232-4ea25eecf7c4)
No idea what this means. (using linux by the way)

**Comment by nosoop** [comment]
Hi; thank you for the report.  Can you mention which version of SourceMod (1.11, 1.12) you're using, and whether or not you're using the 64-bit version of TF2?

The possible issues could be that:

- Newer versions of SourceMod no longer support the ep2v extension.  I feel like I've read that somewhere but since nobody else has reported it, it's probably not that one.
- You're running a 64-bit build of TF2.  At the moment, SourceMod is missing a number of facilities for plugins to work in that environment, and so it's currently not a pressing matter.
    - While not a pressing matter, I do intend to build a 64-bit version in the future.
    - If this is your case, do leave the issue open and it'll be used to track the state of 64-bit TF2Items.

**Comment by Killerman234** [comment]
Using the latest version of source, and I think I am using 64bit. But shit, that sucks.

**Comment by Killerman234** [comment]
How hard would it be to make 64b support for TF2Items?

**Comment by nosoop** [comment]
> How hard would it be to make 64b support for TF2Items?

It should just be changes in `AMBuildScript`.  Identifying the required changes would take some time since the script is from a particularly old AMBuild revision before multiarch was supported.

**Comment by Killerman234** [comment]
Alright well hey, let me know what happens. Appreciate everything

**Comment by Killerman234** [comment]
Have another question, is there anyway I can contact you besides using github?

**Comment by nosoop** [comment]
> Have another question, is there anyway I can contact you besides using github?

Not at the moment &mdash; normally I'd point you to [the AM Forums](https://forums.alliedmods.net/) but I've been slacking off on keeping track of things there.  If you have general questions I'm also occasionally pitching in on the Discord, but I try to avoid one-on-ones for my mental bandwidth.

Status update, by the way; 64-bit binaries can be built using #5 (Windows for sure; Linux untested at this time). There's a few more things necessary to get it release-ready.
